# Generated by Django 6.0.2 on 2026-03-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroponto',
            name='data_referencia',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
