# Generated by Django 6.0.2 on 2026-03-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0002_registroponto_data_referencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroponto',
            name='tipo',
        ),
        migrations.AddField(
            model_name='registroponto',
            name='tipo_marcacao',
            field=models.CharField(choices=[('E1', 'Entrada Inicial'), ('S1', 'Saída para Almoço'), ('E2', 'Volta do Almoço'), ('S2', 'Fim da Jornada')], default='E1', max_length=2),
        ),
    ]
