# Generated by Django 6.0.2 on 2026-03-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0003_remove_registroponto_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroponto',
            name='turno_fechado',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
