# Generated by Django 6.0.2 on 2026-03-08 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0004_registroponto_turno_fechado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroponto',
            options={'ordering': ['data_referencia', 'posicao', '-data_hora'], 'verbose_name': 'Registro de Ponto', 'verbose_name_plural': 'Registros de Ponto'},
        ),
        migrations.RemoveField(
            model_name='registroponto',
            name='turno_fechado',
        ),
        migrations.AddField(
            model_name='registroponto',
            name='posicao',
            field=models.PositiveSmallIntegerField(default=1, editable=False),
        ),
    ]
